apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: password-generator
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: password-generator=ghcr.io/ta1ss/password-generator:latest
    argocd-image-updater.argoproj.io/password-generator.update-strategy: digest
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/ta1ss/password-generator.git'
    targetRevision: master
    path: password-generator
    helm:
      # parameters:
      #   - name:  "ingress.host"
      #     value: "password-generator.example.com"
      #   - name: "ginMode"
      #     value: "debug"
  destination:
    server: https://kubernetes.default.svc
    namespace: password-generator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true