
appName: password-generator
appNamespace: password-generator
replicaCount: 1
ginMode: release

resources:
  requests:
    cpu: 10m
    memory: 100Mi
  limits:
    cpu: 1000m
    memory: 

securityContext:
  fsGroup: 20001
  runAsGroup: 30001
  runAsNonRoot: true
  runAsUser: 10001
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  seccompProfile: |
    { type: "RuntimeDefault" }

image:
  name: ghcr.io/ta1ss/password-generator
  tag: latest

# Registry login creds are needed if using private registry
# Secret can be set 
# kubectl create secret docker-registry imagecredentials --docker-server=DOCKER_REGISTRY_SERVER --docker-username=DOCKER_USER --docker-password=DOCKER_PASSWORD
imagePullSecrets:
  - name: imagecredentials

service:
  protocol: TCP
  port: 80
  targetPort: 8080

ingress:
  host: password-generator.example.com